#!/bin/bash

T=$(mktemp --directory)
clean_up() {
	rm -r $T
}
trap clean_up EXIT

check_for_failure() {
	if [ $1 -eq 0 ]; then
		echo "!!! unexpected success"
		Failed=true
	elif [ "$2" = "$(cat $T/output)" ]; then
		echo "    okay"
	else
		echo "!!! unexpected failure:  $(cat $T/output)"
		Failed=true
	fi
}

# Build the project.
npm run build 

Failed=false
echo It works as expected.
node process-phases.js construction.json design.json permitting.json phases.json > /dev/null
if [ $? -eq 0 ]; then
	echo "    okay"
else
	echo "!!! unexpected failure"
	Failed=true
fi

echo It fails if there are no command line arguments.
node process-phases.js > /dev/null 2> $T/output
check_for_failure $? 'no files provided'

echo It fails if there are not enough command line arguments.
node process-phases.js phases.json > /dev/null 2> $T/output
check_for_failure $? 'insufficient files provided'

echo It fails if the last argument is not phases.json.
node process-phases.js phases.json construction.json design.json permitting.json > /dev/null 2> $T/output
check_for_failure $? 'no phases.json file'

echo "It fails if the number of files doesn't match the number of phases."
node process-phases.js construction.json design.json phases.json > /dev/null 2> $T/output
check_for_failure $? 'invalid file count'

echo "It fails if there is invalid JSON."
echo '[{0}]' > $T/construction.json
node process-phases.js $T/construction.json design.json phases.json > /dev/null 2> $T/output
check_for_failure $? 'Unexpected number in JSON at position 2'

echo "It fails if there are missing phases."
echo '[]' > $T/unspecified.json
node process-phases.js $T/unspecified.json design.json permitting.json phases.json > /dev/null 2> $T/output
check_for_failure $? 'missing phases'

echo "It fails if there is a circular dependency."
sed 's/\[\]/["Finishes"]/' construction.json > $T/construction.json
node process-phases.js $T/construction.json design.json permitting.json phases.json > /dev/null 2> $T/output
check_for_failure $? 'circular dependency'

if $Failed; then
	echo "At least one test failed."
else
	echo "All tests passed."
fi
